# input_device      = "Mikrofonarray (Realtek High Definition Audio(SST))" # optional else default device
# output_device     = "Speaker/HP (Realtek High Definition Audio(SST))" # optional else default device
# loopback_device   = "CABLE Input (VB-Audio Virtual Cable)" # required: change to your virtual loopback output

disable_simultaneous_playback = false # stop currently playing sounds when playing a new sound
stop_hotkey = "CTRL-ALT-E" # stop all sound
