[package]
authors = ["James Birtles <jameshbirtles@gmail.com>", "Karl Skomski <karl@skomski.com>"]
description = "An modified fork of hotkey-rs https://github.com/UnwrittenFun/hotkey-rs for internal usage with the project soundboard"
edition = "2018"
license = "MIT"
name = "hotkey-soundboard"
repository = "https://github.com/gamebooster/soundboard/tree/master/extern/hotkey-rs"
version = "0.0.3"

[dependencies]
thiserror = "1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winuser", "errhandlingapi"]}

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = "2.18"

[target.'cfg(target_os = "macos")'.build-dependencies]
cc = "1"
